[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18"]

[phases.build]
cmds = ["composer install --no-interaction --optimize-autoloader --no-dev", "php artisan storage:link || true"]

[start]
cmd = "php artisan storage:link && php-fpm -D && nginx -g 'daemon off;'"
